FF.FF.FFFFEESEE.
Tests with errors:
------------------
1) TestToto.test8a
example_with_luaunit.lua:81: Bouhouhoum error!
stack traceback:
	example_with_luaunit.lua:81: in function 'funcWithError'
	example_with_luaunit.lua:68: in function 'TestToto.test8a'

2) TestToto.test8b
example_with_luaunit.lua:81: Bouhouhoum error!
stack traceback:
	example_with_luaunit.lua:81: in function 'funcWithError'
	example_with_luaunit.lua:77: in function 'funcWithFuncWithError'
	example_with_luaunit.lua:73: in function 'TestToto.test8b'

3) test1_withAssertionError
example_with_luaunit.lua:134: assertion failed!
stack traceback:
	example_with_luaunit.lua:134: in function 'test1_withAssertionError'

4) test2_withAssertionError
example_with_luaunit.lua:140: assertion failed!
stack traceback:
	example_with_luaunit.lua:140: in function 'test2_withAssertionError'

Failed tests:
-------------
1) TestTiti.test1_withFailure
example_with_luaunit.lua:109: expected: 2, actual: 1
stack traceback:
	example_with_luaunit.lua:109: in function 'TestTiti.test1_withFailure'

2) TestTiti.test2_withFailure
example_with_luaunit.lua:118: expected: "bof"
actual: "hop"
stack traceback:
	example_with_luaunit.lua:118: in function 'TestTiti.test2_withFailure'

3) TestToto.test1_withFailure
example_with_luaunit.lua:21: expected: 2, actual: 1
stack traceback:
	example_with_luaunit.lua:21: in function 'TestToto.test1_withFailure'

4) TestToto.test2_withFailure
example_with_luaunit.lua:30: expected: "bof"
actual: "hop"
stack traceback:
	example_with_luaunit.lua:30: in function 'TestToto.test2_withFailure'

5) TestToto.test4
example_with_luaunit.lua:43: Received the not expected value: 1
stack traceback:
	example_with_luaunit.lua:43: in function 'TestToto.test4'

6) TestToto.test5
example_with_luaunit.lua:49: expected: false or nil, actual: 1
stack traceback:
	example_with_luaunit.lua:49: in function 'TestToto.test5'

7) TestToto.test6
example_with_luaunit.lua:57: expected: false, actual: nil
stack traceback:
	example_with_luaunit.lua:57: in function 'TestToto.test6'

8) TestToto.test7
example_with_luaunit.lua:63: expected: {1, 2, three=3}
actual: {1, 2}
stack traceback:
	example_with_luaunit.lua:63: in function 'TestToto.test7'

Ran 15 tests in 0.000 seconds, 3 successes, 8 failures, 4 errors, 1 skipped
