TestTiti:setUp
some stuff test 1
TestTiti:tearDown
FTestTiti:setUp
some stuff test 2
TestTiti:tearDown
FTestTiti:setUp
some stuff test 3
TestTiti:tearDown
.some stuff test 1
Fsome stuff test 2
Fsome stuff test 3
.some stuff test 4
Fsome stuff test 5
Fsome stuff test 6
FFEEEE.
Tests with errors:
------------------
1) TestToto.test8a
test/legacy_example_with_luaunit.lua:76: Bouhouhoum error!
stack traceback:
	test/legacy_example_with_luaunit.lua:76: in function 'funcWithError'
	test/legacy_example_with_luaunit.lua:63: in function 'TestToto.test8a'

2) TestToto.test8b
test/legacy_example_with_luaunit.lua:76: Bouhouhoum error!
stack traceback:
	test/legacy_example_with_luaunit.lua:76: in function 'funcWithError'
	test/legacy_example_with_luaunit.lua:72: in function 'funcWithFuncWithError'
	test/legacy_example_with_luaunit.lua:68: in function 'TestToto.test8b'

3) test1_withFailure
test/legacy_example_with_luaunit.lua:124: assertion failed!
stack traceback:
	test/legacy_example_with_luaunit.lua:124: in function 'test1_withFailure'

4) test2_withFailure
test/legacy_example_with_luaunit.lua:130: assertion failed!
stack traceback:
	test/legacy_example_with_luaunit.lua:130: in function 'test2_withFailure'

Failed tests:
-------------
1) TestTiti.test1_withFailure
test/legacy_example_with_luaunit.lua:99: expected: 2, actual: 1
stack traceback:
	test/legacy_example_with_luaunit.lua:99: in function 'TestTiti.test1_withFailure'

2) TestTiti.test2_withFailure
test/legacy_example_with_luaunit.lua:108: expected: "bof"
actual: "hop"
stack traceback:
	test/legacy_example_with_luaunit.lua:108: in function 'TestTiti.test2_withFailure'

3) TestToto.test1_withFailure
test/legacy_example_with_luaunit.lua:19: expected: 2, actual: 1
stack traceback:
	test/legacy_example_with_luaunit.lua:19: in function 'TestToto.test1_withFailure'

4) TestToto.test2_withFailure
test/legacy_example_with_luaunit.lua:28: expected: "bof"
actual: "hop"
stack traceback:
	test/legacy_example_with_luaunit.lua:28: in function 'TestToto.test2_withFailure'

5) TestToto.test4
test/legacy_example_with_luaunit.lua:41: Received the not expected value: 1
stack traceback:
	test/legacy_example_with_luaunit.lua:41: in function 'TestToto.test4'

6) TestToto.test5
test/legacy_example_with_luaunit.lua:46: expected: true, actual: 1
stack traceback:
	test/legacy_example_with_luaunit.lua:46: in function 'TestToto.test5'

7) TestToto.test6
test/legacy_example_with_luaunit.lua:52: expected: true, actual: false
stack traceback:
	test/legacy_example_with_luaunit.lua:52: in function 'TestToto.test6'

8) TestToto.test7
test/legacy_example_with_luaunit.lua:58: expected: {1, 2, three=3}
actual: {1, 2}
stack traceback:
	test/legacy_example_with_luaunit.lua:58: in function 'TestToto.test7'

Ran 15 tests in 0.015 seconds, 3 successes, 8 failures, 4 errors
